import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin = "anonymous"/>
        <link href="https://fonts.googleapis.com/css2?family=Aclonica&display=swap" rel="stylesheet"></link>
        <meta name="description" content="Generated by create next app" />
        <script src="https://kit.fontawesome.com/de4a56e816.js" crossOrigin="anonymous" defer></script>
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}